[package]
name = "httpp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
dotenvy = "0.15.7"

reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde_json = "1.0.140"
tokio = { version = "1", features = ["full", "macros"] }
